title: Seon Kim | Research Portfolio
description: Personal Research Portfolio
url: https://kso012.github.io
baseurl: ""
lang: ko
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
exclude:
  - README.md
